Лаб1-4/yii-world/models/Continent.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "continent".
 *
 * @property int $continent_id
 * @property string $code Continent code
 * @property string|null $name
 * @property string $description
 *
 * @property Country[] $countries
 */
class Continent extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'continent';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['code', 'description'], 'required'],
            [['description'], 'string'],
            [['code'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'continent_id' => 'Continent ID',
            'code' => 'Code',
            'name' => 'Name',
            'description' => 'Description',
        ];
    }

    /**
     * Gets query for [[Countries]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCountries()
    {
        return $this->hasMany(Country::className(), ['continent_id' => 'continent_id']);
    }
}

Лаб1-4/yii-world/controllers/ContinentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ContinentSearch;
use app\models\Continent;
use app\models\Country;
use app\models\Region;
use app\models\City;
use app\models\WorldForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * ContinentController implements the CRUD actions for Continent model.
 */
class ContinentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Continent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ContinentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWorldForm()
    {
        $model = new WorldForm();
        $continents = Continent::find()->asArray()->all();
        $continent = null;
        $countries = null;
        $regions = null;
        $cities = null;

        if (Yii::$app->request->isPjax) {
            $model->load(Yii::$app->request->post());
            $continent = Continent::find()->where(['continent_id' => $model->continent_id])->asArray()->one();
            if ($model->continent_id > 0) {
                $countries = Country::find()->where(['continent_id' => $model->continent_id])->asArray()->all();
                
            }
            if($model->country_id > 0){
                    
                $regions = Region::find()
                ->select('region.*, region_language.name_language as name_language')
                ->leftJoin('region_language', '`region_language`.`region_id` = `region`.`region_id`')
                ->where(['region_language.language' => 'en', 'region.country_id' => $model->country_id])
                ->asArray()
                ->all();

            }
            if($model->region_id > 0){

                $cities = City::find()
                ->select('city.*, city_language.name_language as name_language')
                ->leftJoin('city_language', '`city_language`.`city_id` = `city`.`city_id`')
                ->where(['city_language.language' => 'en', 'city.region_id' => $model->region_id])
                ->asArray()
                ->all();
            }
        }

        return $this->render('world-form', [
            'model' => $model,
            'continents' => $continents,
            'continent' => $continent,
            'countries' => $countries,
            'regions' => $regions,
            'cities' => $cities
        ]);
    }

    public function actionList()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('list', ['continents' => $continents]);
    }

    /**
     * Displays a single Continent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($code = 'AF')
    {
        $continent = Continent::find()->where(['code' => $code])->one();

        $countriesProvider = new ActiveDataProvider([
            'query' => Country::find()->where(['continent_id' => $continent->continent_id]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('view', [
            'continent' => $continent,
            'countriesProvider' => $countriesProvider,
            //'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Continent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Continent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->continent_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Continent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->continent_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Continent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Continent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Continent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Continent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

Лаб1-4/yii-world/controllers/CountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Country;
use app\models\CountrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CountrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($code = "UA")
    {
        $country = Country::find()->where(['code' => $code])->one();

        return $this->render('view', [
            'country' => $country,
            //'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Country model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Country();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Country model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

Лаб1-4/yii-world/views/continent/_country.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
?>

<a class='list-group-item' href="<?= Url::to(['country/view', 'code' => $model->code]); ?>">
    <?= Html::img('@web/images/countries/png100px/'. $model['code'] .'.png');?>
    <?php echo $model->name; ?>

</a>

Лаб1-4/yii-world/views/continent/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Continent */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="continent-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

Лаб1-4/yii-world/views/continent/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ContinentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="continent-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'continent_id') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

Лаб1-4/yii-world/views/continent/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Continent */

$this->title = 'Create Continent';
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="continent-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

Лаб1-4/yii-world/views/continent/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ContinentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Continents';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="continent-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Continent', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'continent_id',
            'code',
            'name',
            'description:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

Лаб1-4/yii-world/views/continent/list.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
?>

<div class="container">
    <div class="row">
        <?php foreach($continents as $continentItem): ?>
            <div class="col-md-4" style="min-height: 550px">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>
                            <a href="<?= Url::to(['continent/view', 'code' => $continentItem['code']]); ?>">
                                <?php echo $continentItem['name']; ?>
                            </a>
                        </h2>
                    </div>
                    <div class="panel-body">
                        <?= Html::img('@web/images/continents/'. $continentItem['code'] .'.png', ['width' => '100%']);?>
                        <?php echo $continentItem['description'] ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

Лаб1-4/yii-world/views/continent/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Continent */

$this->title = 'Update Continent: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->continent_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="continent-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

Лаб1-4/yii-world/views/continent/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model app\models\Continent */

$this->title = $continent->name;
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['list']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="continent-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $continent->continent_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $continent->continent_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= DetailView::widget([
        'model' => $continent,
        'attributes' => [
            'continent_id',
            'code',
            'name',
            'description:ntext',
        ],
        ]) ?>

<?= ListView::widget([
    'dataProvider' => $countriesProvider,
    'itemView' => '_country',]);
    ?>

</div>

Лаб1-4/yii-world/views/continent/world-form.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
?>

<?php Pjax::begin([
    'id' => 'world-form-container'
]); ?>
<?php $form = ActiveForm::begin([
    'options' => ['data' => ['pjax' => true],],
    'id' => 'world-form'
]); ?>


<?= $form->field($model, 'continent_id')->dropDownList(ArrayHelper::map($continents, 'continent_id', 'name'), [
    'id' => 'field-continent-id',
    'onchange' => '
        $("#field-region-id").val("");
        $("#field-city-id").val("");
        $("#world-form").submit()'
]) 
?>



<?php if($continent > 0): ?>
    <h2><?= $continent['name'] ?></h2>
    <p><?= $continent['description'] ?></p>
<?php endif; ?>



<?php if($continent > 0){
    echo $form->field($model, 'country_id')->dropDownList(ArrayHelper::map($countries, 'country_id', 'name'), [
        'id' => 'field-country-id',
        'onchange' => '
            $("#field-region-id").val("");
            $("#field-city-id").val("");
            $("#world-form").submit()']);
    }
?>



<?php if($model->country_id == '227'){
    echo $form->field($model, 'region_id')->dropDownList(ArrayHelper::map($regions, 'region_id', 'name_language'), [
        'id' => 'field-region-id',
        'onchange' => '$("#world-form").submit()']);
    }
?>



<?php 
    //var_dump($model);
    if($model->region_id > 1000){
    echo $form->field($model, 'city_id')->dropDownList(ArrayHelper::map($cities, 'city_id', 'name_language'), [
        'id' => 'field-city-id',
        'onchange' => ' $("#world-form").submit()']);
    }
?>



<?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>